image: hwrunner:latest
variables:
    GIT_SSL_NO_VERIFY: "true"
    EXEC: imprimer
    HW_DIR: hw4
before_script:
    - make clean all -C ${HW_DIR}
stages:
    - build
    - run
    - test
build:
    stage: build
    script:
        - echo "Build done"
run:
    stage: run
    script:
        - cd ${HW_DIR} && bin/${EXEC} -i rsrc/imprimer.cmd
test:
    stage: test
    script:
        - cd ${HW_DIR} && bin/${EXEC}_tests --verbose -j1
